### PR TITLE
Flatten package

### PR DESCRIPTION
**Pull request by munshkr**
This removes the unnecesary nesting (`py-vortex/py_vortex`), simplifying installation instructions as well. AFAIK there won't be other implementations of "vortex" for other languages in this repository (every other implementation has its own name and repo, like [Strudel](https://github.com/tidalcycles/strudel)), so it makes sense to just have the package source at the root.

### CODE REVIEW

**Comment by munshkr** [comment]
We could rename `py_vortex` to `vortex` as well, if you agree.

**Comment by yaxu** [comment]
Yes that's fine by me

**Comment by munshkr** [comment]
Just renamed the packaged, I think it looks simpler now!

**Comment by yaxu** [comment]
Great. You have merge permissions right?

**Pull request merged**
